### ISSUE TITLE
Adding a csp nonce to the generated inline script

### ISSUE THREAD

**Issue by seanconn** [miranj/craft-obfuscator#11]
The inline script generated by obfuscator does not work with my content security policy as I am using csp nonces which prevents any inline scripts that are not nonced from working. Is there any way to get a csp nonce included in the script?

I'm using the following plugin: https://plugins.craftcms.com/content-security-policy

and adding nonces to inline scripts with this code:

{%  script with { nonce: cspNonce('script-src') } %}

**Comment by rungta** [comment]
Hi @seanconn, you should be able to add the `nonce` attribute manually to all generated inline script tags using [the Retcon plugin’s](https://github.com/mmikkel/Retcon-Craft) [`retconAttr` filter](https://github.com/mmikkel/Retcon-Craft/wiki/Attr), like so:

```twig
{{ someHtmlWithEmails
    | enkode_emails
    | retconAttr(
        'script[id^=script_enkoder_]',
        { noonce: cspNonce('script-src') }
    )
}}
```
