### ISSUE TITLE
Could you please increase the email regex limit to 8 ?

### ISSUE THREAD

**Issue by elodiegrondin** [miranj/craft-obfuscator#3]
https://github.com/miranj/craft-obfuscator/blob/90168ac6798be5d864e04952eb5d415e9bd18daa/lib/StandalonePHPEnkoder.php#L78

Could you please increase the email regex limit to 8 ? Because I have several email address like info@sprb.brussels so the 2 last characters are out of <a> tag. I made the change in my project but it could be useful to have it by default in case of update.

```
$this->email_regex = '[\w\d+_.-]+@(?:[\w\d_-]+\.)+[\w]{2,8}';
```

Thank you, it's a great plugin ! :)

**Comment by rungta** [comment]
Fixed in 1.0.4. Thanks for reporting @elodiegrondin!
