### ISSUE TITLE
enkode_emails filter doesn’t work on complicated markup

### ISSUE THREAD

**Issue by medoingthings** [miranj/craft-obfuscator#4]
Hi there,

just tried out your really helpful plugin. Much appreciated, thanks!

However, I noticed that the following code doesn’t obfuscate all email addresses as expected

    {% filter enkode_emails %}
      <a href="mailto:{{ recipient }}">
        <span>{{ recipient}}</span>
      </a>
    {% endfilter %}

However, this makes it work:

    {% filter enkode_emails %}{% spaceless %}
      <a href="mailto:{{ recipient }}">
        <span>{{ recipient}}</span>
      </a>
    {% endspaceless %}{% endfilter %}

So there might be a simple fix for that. The `enkode` filter works like a charm though.

Cheers and thanks for your efforts,
Mark

**Comment by rungta** [comment]
Hi Mark, thank you for reporting the bug. We’ll try and take a look sometime in the near future and get back to you.

**Comment by rungta** [comment]
This slipped from our radar but we finally got to it. Obfuscator 1.1.1 is out now with the fix.
