### ISSUE TITLE
Support for Craft 5

### ISSUE THREAD

**Issue by mereditsommer** [miranj/craft-obfuscator#9]
Do you plan on updating the Plugin for Craft 5?
Thanks in advance.

**Comment by rungta** [comment]
Yes, we plan on updating all our plugins to support Craft 5.

**Comment by mereditsommer** [comment]
Thanks! Do you have an estimate, when you'll be ready, approximately?

**Comment by rungta** [comment]
We’re targeting getting this done in the ongoing month of April, hopefully in a week or two.

**Comment by lindseydiloreto** [comment]
Excited to see the Craft 5 version, it's one of the last C4-only plugins in our starter project.

Thanks for your hard work on this great little plugin!

**Comment by lindseydiloreto** [comment]
I've just submitted a [PR](https://github.com/miranj/craft-obfuscator/pull/10) for Craft 5 compatibility. Everything was thoroughly tested on my local machine, I can confirm that it works as expected on Craft 5.

Amazingly, there were zero changes required beyond marking it as Craft 5 compatible!

Hope that helps, thanks again for providing this plugin! 🍺

**Comment by rungta** [comment]
We’ve just pushed out [v1.2.0](https://github.com/miranj/craft-obfuscator/releases/tag/v1.2.0) which adds Craft 5 compatibility for the Obfuscator plugin.

Thank you for the patience @mereditsommer, and for the help @lindseydiloreto.
